export const userActionTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SET_EMPLOYEE_LIST: "SET_EMPLOYEE_LIST",
    SET_AGENCY_LIST: "SET_AGENCY_LIST",
    SET_NAME_PHONE: "SET_NAME_PHONE",
    SET_PAYMENT_DATA: "SET_PAYMENT_DATA"
}
